Fix scans
awslabs/amazon-s3-glacier-refreezer pull request #59
Opened 2022-11-22 04:20 UTC by G-Lenz

*Description of changes:*
- Pulled out policies from default role policies that did not satisfy SPCM limits for cfn nag scans and placed them in a separate defined policy attached to the role.
- Put back build-open-source-dist.sh in order for pipeline to complete properly.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-22 17:56 UTC, dimitri-lopez commented on deployment/build-open-source-dist.sh
> +cp $source_template_dir/../LICENSE.txt $dist_dir
Create another variable for the directory `$source_template_dir/..`. Would make the following code a little easier to follow.

2022-11-22 17:58 UTC, dimitri-lopez approved these changes

2022-11-28 18:47 UTC, gsingh04 commented on buildspec.yml
> +      - chmod +x ./build-open-source-dist.sh && ./build-open-source-dist.sh $SOLUTION_NAME
i believe this was intentionally removed as we don't need to run the open source script with github first approach

2022-11-28 19:00 UTC, G-Lenz commented on buildspec.yml
> +      - chmod +x ./build-open-source-dist.sh && ./build-open-source-dist.sh $SOLUTION_NAME
It was intentionally removed but we decided to put it back because the build pipeline failed without it during the deploy assets stage.

2022-11-28 19:02 UTC, G-Lenz commented on deployment/build-open-source-dist.sh
> +cp $source_template_dir/../LICENSE.txt $dist_dir
This was added back exactly as it was. Refactoring this file is outside of the scope of this PR, but we can add it to the backlog.

2022-11-28 19:18 UTC, gsingh04 approved these changes

2022-11-29 16:09 UTC, schana requested changes
Can we consolidate the commits to have one for the re-adding the open-source script and another for the IAM changes?

2022-12-01 16:20 UTC, schana approved these changes

2022-12-05 15:36 UTC, merged